# Generated by Django 5.0.4 on 2024-04-26 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YD_Class',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('daily_rental_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weekly_rental_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('class_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='YD_Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('license_no', models.CharField(max_length=20)),
                ('state_issued', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=100)),
                ('cc_type', models.CharField(max_length=20)),
                ('cc_number', models.CharField(max_length=16)),
                ('cc_exp_month', models.IntegerField()),
                ('cc_exp_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='YD_Location',
            fields=[
                ('location_id', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_no', models.CharField(max_length=15)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_customer')),
            ],
        ),
        migrations.CreateModel(
            name='YD_Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_location')),
            ],
        ),
        migrations.CreateModel(
            name='YD_Model',
            fields=[
                ('model_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_class')),
            ],
        ),
        migrations.CreateModel(
            name='YD_Car',
            fields=[
                ('vin', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_class')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_location')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_model')),
            ],
        ),
        migrations.CreateModel(
            name='YD_RentalAgreement',
            fields=[
                ('contract_no', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('end_time', models.DateTimeField()),
                ('odo_read_start', models.IntegerField()),
                ('odo_read_end', models.IntegerField()),
                ('rental_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_customer')),
            ],
        ),
        migrations.CreateModel(
            name='YD_RentalAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_rentalagreement')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_customer')),
                ('vin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_car')),
            ],
        ),
        migrations.CreateModel(
            name='YD_Reservation',
            fields=[
                ('reservation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pick_up_date', models.DateField()),
                ('pickup_time', models.DateTimeField()),
                ('drop_off_date', models.DateField()),
                ('dropoff_time', models.DateTimeField()),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_class')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_customer')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_employee')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_location')),
            ],
        ),
        migrations.AddField(
            model_name='yd_rentalagreement',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yourdrive.yd_reservation'),
        ),
    ]
